In [3]:
# %pip install -U ultralytics

In [2]:
# Import of all packages
import ultralytics
from ultralytics import YOLO
import shutil
import zipfile
from pathlib import Path
import yaml
from google.colab import drive

drive.mount("/content/drive")

Creating new Ultralytics Settings v0.0.8 file ✅
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart#ultralytics-settings.
Mounted at /content/drive

In [8]:
# Here are done some configurations and openning of files

DRIVE_ZIP = Path(
    "/content/drive/MyDrive/DLE/taco_yolo.zip" # Same as taco_yolo_initial_split
)
LOCAL_ZIP = Path("/content/taco_yolo.zip")
DATASET_DIR = Path("/content/taco_yolo")

shutil.copy2(DRIVE_ZIP, LOCAL_ZIP)

with zipfile.ZipFile(LOCAL_ZIP) as archive:
    archive.extractall("/content")

DATA_YAML = DATASET_DIR / "data.yaml"

with DATA_YAML.open(encoding="utf-8") as file:
    dataset_config = yaml.safe_load(file)

dataset_config["path"] = str(DATASET_DIR)

with DATA_YAML.open("w", encoding="utf-8") as file:
    yaml.safe_dump(
        dataset_config,
        file,
        sort_keys=False,
        allow_unicode=True,
    )

In [ ]:
# The configuration of images for first two trainings were with train/val/test of 80/10/10(1200/150/150)
# For further training, I want to try 4-fold cross-validation, doing only train/test of 90/10(1350/150)

IMAGE_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".bmp", ".webp"
}

for split in ("train", "test"):
    image_directory = DATASET_DIR / "images" / split
    label_directory = DATASET_DIR / "labels" / split

    images = [
        path
        for path in image_directory.rglob("*")
        if path.suffix.lower() in IMAGE_EXTENSIONS
    ]

    labels = list(label_directory.rglob("*.txt"))

    print(
        f"{split:5s}: "
        f"{len(images):4d} images, "
        f"{len(labels):4d} label files"
    )

train: 1200 images, 1200 label files
test :  150 images,  150 label files

In [ ]:
# Training of the model with different parameters
DRIVE_RUNS = Path(
    "/content/drive/MyDrive/YOLO/runs"
)
DRIVE_RUNS.mkdir(parents=True, exist_ok=True)

model = YOLO("yolo26n.pt")

training_results = model.train(
    data=str(DATA_YAML),
    epochs=1,
    imgsz=960,
    batch=8,
    # device=0,
    patience=30,
    optimizer="auto",
    amp=True,
    workers=2,
    cache=False,
    seed=42,
    plots=True,
    save=True,
    save_period=10,
    project=str(DRIVE_RUNS),
    name="taco10_yolo26n",
)

RUN_DIRECTORY = Path(model.trainer.save_dir)
print("Results saved to:", RUN_DIRECTORY)

Ultralytics 8.4.117 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/taco_yolo/data.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=1, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=960, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=taco10_yolo26n-3, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO/runs, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3, save_frames=False, save_json=False, save_period=10, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 16.8MB/s 0.0s
Overriding model.yaml nc=80 with nc=10

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245076  ultralytics.nn.modules.head.Detect           [10, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,507,700 parameters, 2,507,700 gradients, 5.9 GFLOPs

Remapped 2/10 cls head rows from pretrained weights by class name
Transferred 612/708 items from pretrained weights
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2834.8±432.6 MB/s, size: 1722.4 KB)
train: Scanning /content/taco_yolo/labels/train/batch_1... 1200 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1200/1200 1.7Kit/s 0.7s
train: New cache created: /content/taco_yolo/labels/train/batch_1.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2999.7±382.6 MB/s, size: 1833.5 KB)
val: Scanning /content/taco_yolo/labels/val/batch_1... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 1.9Kit/s 0.1s
val: New cache created: /content/taco_yolo/labels/val/batch_1.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3/labels.jpg...
Image sizes 960 train, 960 val
Using 0 dataloader workers
Logging results to /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3
Starting training for 1 epochs...

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
        1/1         0G      1.466      7.676   0.006248         36        960: 100% ━━━━━━━━━━━━ 150/150 16.3s/it 40:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 11.1s/it 1:51
                   all        150        487      0.667     0.0564     0.0492     0.0344

1 epochs completed in 0.710 hours.
Optimizer stripped from /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3/weights/last.pt, 5.4MB
Optimizer stripped from /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3/weights/best.pt, 5.4MB

Validating /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3/weights/best.pt...
Ultralytics 8.4.117 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 8.1s/it 1:21
                   all        150        487      0.667      0.057     0.0492     0.0345
                 Other         84        212      0.381     0.0708     0.0956     0.0618
                Bottle         33         44     0.0724      0.255     0.0858     0.0566
            Bottle cap         27         39          1          0     0.0434     0.0309
                   Can         18         27          1     0.0704      0.115     0.0928
                   Cup         12         14          0          0    0.00232    0.00133
                   Lid          4          5          1          0     0.0245    0.00625
 Plastic bag + wrapper         44         75      0.221      0.173      0.107     0.0788
               Pop tab          7          8          1          0     0.0179     0.0161
                 Straw         14         19          1          0   0.000934   0.000297
             Cigarette         15         44          1          0          0          0
Speed: 12.7ms preprocess, 445.9ms inference, 0.0ms loss, 0.1ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3
Results saved to: /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3

In [ ]:
# First training
# epochs=100,
# imgsz=640,

RUN_DIRECTORY = Path(
    "/content/drive/MyDrive/YOLO/runs/taco10_yolo26n"
)

BEST_WEIGHTS = RUN_DIRECTORY / "weights" / "best.pt"

best_model = YOLO(str(BEST_WEIGHTS))

test_metrics = best_model.val(
    data=str(DATA_YAML),
    split="test",
    imgsz=640,
    device=0,
)

print("mAP50:", test_metrics.box.map50)
print("mAP50–95:", test_metrics.box.map)

Ultralytics 8.4.116 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 28.0MB/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 189.6±58.6 MB/s, size: 1811.1 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 404.2it/s 0.4s
val: New cache created: /content/taco_yolo/labels/test/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 1.1it/s 9.0s
                   all        150        485      0.298      0.233      0.209      0.149
                 Other         69        159      0.218      0.258      0.154      0.101
                Bottle         39         54      0.511      0.463      0.443      0.347
            Bottle cap         28         32       0.59       0.27      0.295      0.161
                   Can         20         26      0.303      0.385      0.244      0.195
                   Cup         16         20      0.342       0.25      0.277      0.182
                   Lid          8          9      0.154      0.111      0.116      0.115
 Plastic bag + wrapper         56         86      0.363      0.465      0.371      0.264
               Pop tab          6          6          0          0   0.000609   0.000365
                 Straw         14         15      0.277     0.0667      0.116     0.0847
             Cigarette         26         78      0.222     0.0641     0.0743     0.0352
Speed: 4.0ms preprocess, 9.0ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/runs/detect/val
mAP50: 0.2090984549705266
mAP50–95: 0.14867631425497482

In [ ]:
# Second training (we can see a small improvement)
# epochs=50,
# imgsz=960,

RUN_DIRECTORY2 = Path(
    "/content/drive/MyDrive/YOLO/runs/taco10_yolo26n-2"
)

BEST_WEIGHTS2 = RUN_DIRECTORY2 / "weights" / "best.pt"

best_model2 = YOLO(str(BEST_WEIGHTS2))

test_metrics2 = best_model2.val(
    data=str(DATA_YAML),
    split="test",
    imgsz=960,
    device=0,
)

print("mAP50:", test_metrics2.box.map50)
print("mAP50–95:", test_metrics2.box.map)

Ultralytics 8.4.117 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 26.4MB/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 174.6±45.2 MB/s, size: 1191.6 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 431.5it/s 0.3s
val: New cache created: /content/taco_yolo/labels/test/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 10/10 1.1s/it 10.6s
                   all        150        485      0.359       0.28      0.215      0.154
                 Other         69        159      0.264      0.302      0.182      0.128
                Bottle         39         54      0.481      0.537      0.464      0.333
            Bottle cap         28         32      0.481       0.29      0.359       0.24
                   Can         20         26      0.295      0.306      0.309      0.244
                   Cup         16         20      0.231        0.4      0.168      0.129
                   Lid          8          9        0.1      0.222     0.0394     0.0257
 Plastic bag + wrapper         56         86      0.413      0.507      0.395      0.265
               Pop tab          6          6          1          0     0.0165     0.0132
                 Straw         14         15       0.12      0.133      0.125      0.106
             Cigarette         26         78      0.199      0.103      0.088     0.0513
Speed: 12.8ms preprocess, 12.8ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/runs/detect/val
mAP50: 0.21465410873284144
mAP50–95: 0.15350919845157177

In [9]:
# Once analysed the previous values, to improve the performance, I decided to apply cross-validation
# That is why I modified the dataset, putting all the validation data together with training.
# It is applied a four-cross validation to try to improve the results

# Here are done some configurations and openning of files

DRIVE_ZIP2 = Path(
    "/content/drive/MyDrive/DLE/taco_yolo_test_train.zip" # Same as taco_yolo_test_train
)
LOCAL_ZIP2 = Path("/content/taco_yolo_test_train.zip")
DATASET_DIR2 = Path("/content/taco_yolo_test_train")

shutil.copy2(DRIVE_ZIP2, LOCAL_ZIP2)

with zipfile.ZipFile(LOCAL_ZIP2) as archive2:
    archive2.extractall("/content")

DATA_YAML2 = DATASET_DIR2 / "data.yaml"

with DATA_YAML2.open(encoding="utf-8") as file2:
    dataset_config2 = yaml.safe_load(file2)

dataset_config2["path"] = str(DATASET_DIR2)

with DATA_YAML2.open("w", encoding="utf-8") as file2:
    yaml.safe_dump(
        dataset_config2,
        file2,
        sort_keys=False,
        allow_unicode=True,
    )

In [7]:
from sklearn.model_selection import KFold

# Only the training portion—not the test images.
TRAIN_IMAGES_DIR = DATASET_DIR2 / "images" / "train"

FOLDS_DIRECTORY = DATASET_DIR2 / "cross_validation"
FOLDS_DIRECTORY.mkdir(parents=True, exist_ok=True)

IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

training_images = sorted(
    path.resolve()
    for path in TRAIN_IMAGES_DIR.rglob("*")
    if path.suffix.lower() in IMAGE_EXTENSIONS
)

print("Images available for cross-validation:", len(training_images))

with open(DATA_YAML2, encoding="utf-8") as file:
    original_configuration = yaml.safe_load(file)

class_names = original_configuration["names"]

kfold = KFold(
    n_splits=4,
    shuffle=True,
    random_state=42,
)

fold_yamls = []

for fold_number, (train_indices, val_indices) in enumerate(
    kfold.split(training_images),
    start=1,
):
    fold_directory = FOLDS_DIRECTORY / f"fold_{fold_number}"
    fold_directory.mkdir(parents=True, exist_ok=True)

    fold_train_images = [
        training_images[index] for index in train_indices
    ]
    fold_val_images = [
        training_images[index] for index in val_indices
    ]

    train_txt = fold_directory / "train.txt"
    val_txt = fold_directory / "val.txt"

    train_txt.write_text(
        "\n".join(str(path) for path in fold_train_images) + "\n"
    )
    val_txt.write_text(
        "\n".join(str(path) for path in fold_val_images) + "\n"
    )

    fold_yaml = fold_directory / "data.yaml"

    fold_configuration = {
        "path": str(DATASET_DIR2.resolve()),
        "train": str(train_txt.resolve()),
        "val": str(val_txt.resolve()),
        "names": class_names,
    }

    with open(fold_yaml, "w", encoding="utf-8") as file:
        yaml.safe_dump(
            fold_configuration,
            file,
            sort_keys=False,
        )

    fold_yamls.append(fold_yaml)

    print(
        f"Fold {fold_number}: "
        f"{len(fold_train_images)} train, "
        f"{len(fold_val_images)} validation"
    )

Images available for cross-validation: 1350
Fold 1: 1012 train, 338 validation
Fold 2: 1012 train, 338 validation
Fold 3: 1013 train, 337 validation
Fold 4: 1013 train, 337 validation

In [ ]:
# Training of the model with different parameters
DRIVE_RUNS = Path(
    "/content/drive/MyDrive/YOLO/runs"
)
DRIVE_RUNS.mkdir(parents=True, exist_ok=True)

model = YOLO("yolo26n.pt")

training_results = model.train(
    data=str(DATA_YAML),
    epochs=1,
    imgsz=960,
    batch=8,
    # device=0,
    patience=30,
    optimizer="auto",
    amp=True,
    workers=2,
    cache=False,
    seed=42,
    plots=True,
    save=True,
    save_period=10,
    project=str(DRIVE_RUNS),
    name="taco10_yolo26n",
)

RUN_DIRECTORY = Path(model.trainer.save_dir)
print("Results saved to:", RUN_DIRECTORY)

In [ ]:
DRIVE_RUNS2 = Path(
    "/content/drive/MyDrive/YOLO_2/runs/cross_validation"
)
DRIVE_RUNS2.mkdir(parents=True, exist_ok=True)

fold_results = []

for fold_number, fold_yaml in enumerate(fold_yamls, start=1):
    print(f"\nTraining fold {fold_number}/4")

    # Important: reset to the same pretrained weights for every fold.
    model = YOLO("yolo26n.pt")

    model.train(
        data=str(fold_yaml),
        epochs=50,
        imgsz=960,
        batch=8,
        # device=0,
        patience=30,
        optimizer="auto",
        amp=True,
        workers=2,
        cache=False,
        seed=42,
        deterministic=True,
        plots=True,
        save=True,
        save_period=-1,
        project=str(DRIVE_RUNS2),
        name=f"taco10_yolo26n_fold_{fold_number}",
    )

Training fold 1/4
Ultralytics 8.4.120 🚀 Python-3.12.13 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
engine/trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=8, bgr=0.0, box=7.5, cache=False, cfg=None, channels_last=False, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, cls_remap=True, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=/content/taco_yolo_test_train/cross_validation/fold_1/data.yaml, degrees=0.0, deterministic=True, device=, dfl=1.5, dgrad=0.5, dis=6.0, distill_model=None, dlam=1.0, dlog=1.0, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=50, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=960, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26n.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=taco10_yolo26n_fold_1-2, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=30, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=/content/drive/MyDrive/YOLO_2/runs/cross_validation, quantize=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=/content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1-2, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=42, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=detect, time=None, tracker=tracktrack.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=2, workspace=None
Overriding model.yaml nc=80 with nc=10

                   from  n    params  module                                       arguments
  0                  -1  1       464  ultralytics.nn.modules.conv.Conv             [3, 16, 3, 2]
  1                  -1  1      4672  ultralytics.nn.modules.conv.Conv             [16, 32, 3, 2]
  2                  -1  1      6640  ultralytics.nn.modules.block.C3k2            [32, 64, 1, False, 0.25]
  3                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
  4                  -1  1     26080  ultralytics.nn.modules.block.C3k2            [64, 128, 1, False, 0.25]
  5                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
  6                  -1  1     87040  ultralytics.nn.modules.block.C3k2            [128, 128, 1, True]
  7                  -1  1    295424  ultralytics.nn.modules.conv.Conv             [128, 256, 3, 2]
  8                  -1  1    346112  ultralytics.nn.modules.block.C3k2            [256, 256, 1, True]
  9                  -1  1    164608  ultralytics.nn.modules.block.SPPF            [256, 256, 5, 3, True]
 10                  -1  1    249728  ultralytics.nn.modules.block.C2PSA           [256, 256, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  1    119808  ultralytics.nn.modules.block.C3k2            [384, 128, 1, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  1     34304  ultralytics.nn.modules.block.C3k2            [256, 64, 1, True]
 17                  -1  1     36992  ultralytics.nn.modules.conv.Conv             [64, 64, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  1     95232  ultralytics.nn.modules.block.C3k2            [192, 128, 1, True]
 20                  -1  1    147712  ultralytics.nn.modules.conv.Conv             [128, 128, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1    463104  ultralytics.nn.modules.block.C3k2            [384, 256, 1, True, 0.5, True]
 23        [16, 19, 22]  1    245076  ultralytics.nn.modules.head.Detect           [10, 1, True, [64, 128, 256]]
YOLO26n summary: 260 layers, 2,507,700 parameters, 2,507,700 gradients, 5.9 GFLOPs

Remapped 2/10 cls head rows from pretrained weights by class name
Transferred 612/708 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed ✅
train: Fast image access ✅ (ping: 0.0±0.0 ms, read: 2297.3±303.0 MB/s, size: 1313.2 KB)
train: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 1012 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 1012/1012 1.5Kit/s 0.7s
train: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01, method='weighted_average', num_output_channels=3), CLAHE(p=0.01, clip_limit=(1.0, 4.0), tile_grid_size=(8, 8))
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 639.8±36.0 MB/s, size: 2288.4 KB)
val: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 338 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 338/338 565.5it/s 0.6s
val: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 114 weight(decay=0.0), 126 weight(decay=0.0005), 126 bias(decay=0.0)
Plotting labels to /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1-2/labels.jpg...
Image sizes 960 train, 960 val
Using 2 dataloader workers
Logging results to /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1-2
Starting training for 50 epochs...

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       1/50      4.87G      1.349       7.87   0.005586         17        960: 100% ━━━━━━━━━━━━ 127/127 1.0s/it 2:11
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 2.4s/it 52.0s
                   all        338       1031      0.431     0.0417     0.0314     0.0244

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       2/50      5.74G      1.342      6.738   0.005768         54        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:39
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1s/it 23.8s
                   all        338       1031      0.519     0.0718     0.0492     0.0364

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       3/50      5.74G      1.369      6.137   0.005679          7        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.5s
                   all        338       1031       0.42      0.102     0.0597     0.0451

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       4/50      5.74G      1.401      5.547   0.006013         28        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:37
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.0it/s 21.6s
                   all        338       1031      0.564      0.136     0.0962     0.0718

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       5/50      5.74G      1.393      4.864   0.005664         33        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.7s
                   all        338       1031      0.526       0.13      0.103      0.077

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       6/50      5.74G      1.388      4.474   0.005853         55        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.1s
                   all        338       1031      0.469      0.142      0.117     0.0836

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       7/50      5.74G      1.388      4.069   0.005859         23        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:39
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.0s/it 23.0s
                   all        338       1031      0.445      0.179      0.122     0.0917

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       8/50      5.74G      1.335      3.697   0.005702         79        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.4s
                   all        338       1031      0.531      0.171      0.146      0.108

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
       9/50      5.74G      1.375      3.472   0.005538         10        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.8s
                   all        338       1031      0.554      0.177      0.178      0.128

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      10/50      5.74G      1.355      3.226   0.005569         21        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:35
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.6s
                   all        338       1031      0.424      0.216      0.175      0.133

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      11/50      5.74G       1.35      3.044   0.005845         26        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.3it/s 17.5s
                   all        338       1031      0.364      0.252      0.188      0.138

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      12/50      5.74G      1.306      2.872   0.005348         13        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.0it/s 21.1s
                   all        338       1031      0.409       0.22      0.182      0.131

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      13/50      5.74G      1.274      2.799   0.005525         12        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:30
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.6s
                   all        338       1031      0.265      0.283      0.202       0.15

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      14/50      5.74G      1.306      2.672   0.005171         12        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 17.7s
                   all        338       1031      0.266      0.304      0.207      0.149

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      15/50      5.74G      1.274      2.558    0.00535          9        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.4s
                   all        338       1031      0.273      0.294      0.211      0.153

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      16/50      5.74G      1.276       2.55    0.00548         16        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.6s
                   all        338       1031      0.328      0.272      0.214      0.155

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      17/50      5.74G       1.31      2.444   0.005386         29        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.6s
                   all        338       1031       0.36      0.286      0.232      0.168

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      18/50      5.74G      1.273      2.375   0.005131         15        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.2s
                   all        338       1031       0.31      0.297      0.243      0.172

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      19/50      5.74G      1.284      2.323   0.005216         37        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:30
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.7s
                   all        338       1031      0.308      0.289      0.222      0.158

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      20/50      5.74G       1.29      2.296     0.0048         21        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:40
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.7s
                   all        338       1031       0.35      0.296      0.251      0.179

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      21/50      5.74G      1.268      2.185    0.00505         24        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:36
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.4s
                   all        338       1031      0.287      0.305      0.226      0.173

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      22/50      5.74G      1.278      2.174   0.004865         20        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.9s
                   all        338       1031      0.305      0.331      0.234      0.174

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      23/50      5.74G      1.222      2.046   0.004879         31        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.0s
                   all        338       1031      0.347      0.301      0.275      0.198

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      24/50      5.74G      1.246      2.037   0.004672         10        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.0s/it 22.0s
                   all        338       1031      0.381      0.324      0.272      0.192

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      25/50      5.74G      1.234      2.036   0.004661         16        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.4s
                   all        338       1031      0.336      0.303      0.258      0.185

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      26/50      5.74G       1.23      2.018   0.004659         32        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.1s
                   all        338       1031      0.392      0.262      0.262      0.191

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      27/50      5.74G      1.231      1.953   0.004636         18        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.4s
                   all        338       1031      0.375      0.316      0.274      0.198

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      28/50      5.74G      1.193      1.919   0.004482         20        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:35
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.9s
                   all        338       1031      0.347       0.34      0.273      0.201

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      29/50      5.74G      1.247      1.867    0.00466         19        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.2s
                   all        338       1031      0.387       0.31      0.279      0.203

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      30/50      5.74G      1.196      1.826   0.004592         17        960: 100% ━━━━━━━━━━━━ 127/127 1.3it/s 1:34
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 20.3s
                   all        338       1031      0.422      0.297      0.278      0.202

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      31/50      5.74G      1.193      1.784   0.004575         12        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:31
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.0it/s 21.3s
                   all        338       1031      0.413      0.269      0.273      0.199

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      32/50      5.74G      1.179      1.781   0.004311         44        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:32
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.1it/s 19.7s
                   all        338       1031      0.467      0.273       0.27      0.202

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size
      33/50      5.74G      1.216       1.76    0.00403         25        960: 100% ━━━━━━━━━━━━ 127/127 1.4it/s 1:33
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 22/22 1.2it/s 18.3s
                   all        338       1031      0.301      0.331      0.271      0.203

      Epoch    GPU_mem   box_loss   cls_loss    l1_loss  Instances       Size

In [11]:
# As it couldn't get executed in one execution because time limits in Collab
# it have been executed since last checkpoint

fold4_directory = (
    DRIVE_RUNS2 / "taco10_yolo26n_fold_4"
)

last_weights = (
    fold4_directory / "weights" / "last.pt"
)

print("Checkpoint:", last_weights)
print("Exists:", last_weights.exists())

model4 = YOLO(str(last_weights))
resume_results4 = model4.train(resume=True)

In [17]:
# Here we represent the results of 4 folder

fold_results = []

for fold_number, fold_yaml in enumerate(fold_yamls, start=1):
    best_weights = (
        DRIVE_RUNS2
        / f"taco10_yolo26n_fold_{fold_number}"
        / "weights"
        / "best.pt"
    )

    print(f"Validating fold {fold_number}")
    print("Weights:", best_weights)

    best_model = YOLO(str(best_weights))

    metrics = best_model.val(
        data=str(fold_yaml),
        split="val",
        imgsz=960,
        batch=8,
        workers=2,
        plots=False,
        verbose=False,
    )

    fold_results.append({
        "fold": fold_number,
        "precision": metrics.box.mp,
        "recall": metrics.box.mr,
        "mAP50": metrics.box.map50,
        "mAP50-95": metrics.box.map,
    })

cv_results = pd.DataFrame(fold_results)
display(cv_results)

display(
    cv_results[
        ["precision", "recall", "mAP50", "mAP50-95"]
    ].agg(["mean", "std"])
)

Validating fold 1
Weights: /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1/weights/best.pt
Ultralytics 8.4.121 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.1±0.0 ms, read: 842.3±172.9 MB/s, size: 1745.4 KB)
val: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 338 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 338/338 1.0Kit/s 0.3s
val: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 43/43 3.7s/it 2:37
                   all        338       1031      0.405      0.337      0.303      0.236
Speed: 4.4ms preprocess, 388.0ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating fold 2
Weights: /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_2/weights/best.pt
Ultralytics 8.4.121 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 990.1±846.0 MB/s, size: 1504.8 KB)
val: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 338 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 338/338 1.5Kit/s 0.2s
val: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 43/43 3.8s/it 2:43
                   all        338       1080      0.382      0.261      0.242      0.184
Speed: 4.2ms preprocess, 400.5ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating fold 3
Weights: /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_3/weights/best.pt
Ultralytics 8.4.121 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 152.6±33.9 MB/s, size: 1213.5 KB)
val: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 337 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 337/337 1.5Kit/s 0.2s
val: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 43/43 3.6s/it 2:36
                   all        337        988      0.357      0.308      0.279      0.213
Speed: 4.2ms preprocess, 384.2ms inference, 0.0ms loss, 0.1ms postprocess per image
Validating fold 4
Weights: /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_4/weights/best.pt
Ultralytics 8.4.121 🚀 Python-3.12.13 torch-2.11.0+cpu CPU (Intel Xeon CPU @ 2.20GHz)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 878.1±651.9 MB/s, size: 1688.0 KB)
val: Scanning /content/taco_yolo_test_train/labels/train/batch_1... 337 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 337/337 1.4Kit/s 0.2s
val: New cache created: /content/taco_yolo_test_train/labels/train/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 43/43 3.6s/it 2:35
                   all        337       1200      0.347      0.291      0.256      0.197
Speed: 4.2ms preprocess, 381.9ms inference, 0.0ms loss, 0.1ms postprocess per image

   fold  precision    recall     mAP50  mAP50-95
0     1   0.404787  0.337383  0.303204  0.235606
1     2   0.381720  0.261322  0.241957  0.183829
2     3   0.357015  0.308492  0.279427  0.213292
3     4   0.347436  0.291117  0.255677  0.197291

      precision    recall     mAP50  mAP50-95
mean   0.372740  0.299578  0.270066  0.207504
std    0.025789  0.031853  0.026975  0.022271

It have been some days since this last execution, so to get some order and make the comparison fair let's add a training with same amount of validation images.

In [5]:
search_directories = [
    Path("/content/drive/MyDrive/YOLO"),
    Path("/content/drive/MyDrive/YOLO_2"),
]

for directory in search_directories:
    if directory.exists():
        for checkpoint in sorted(
            directory.glob("**/weights/best.pt")
        ):
            print(checkpoint)

/content/drive/MyDrive/YOLO/runs/taco10_yolo26n/weights/best.pt
/content/drive/MyDrive/YOLO/runs/taco10_yolo26n-2/weights/best.pt
/content/drive/MyDrive/YOLO/runs/taco10_yolo26n-3/weights/best.pt
/content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1/weights/best.pt
/content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_2/weights/best.pt
/content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_3/weights/best.pt
/content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_4/weights/best.pt

In [6]:
TRAINING_1_WEIGHTS = Path(
    "/content/drive/MyDrive/YOLO/runs/"
    "taco10_yolo26n/weights/best.pt"
)

TRAINING_2_WEIGHTS = Path(
    "/content/drive/MyDrive/YOLO/runs/"
    "taco10_yolo26n-2/weights/best.pt"
)

CV_RUNS_DIRECTORY = Path(
    "/content/drive/MyDrive/YOLO_2/runs/cross_validation"
)

candidates = [
    {
        "model": "Training 1",
        "group": "single_split",
        "weights": TRAINING_1_WEIGHTS,
    },
    {
        "model": "Training 2",
        "group": "single_split",
        "weights": TRAINING_2_WEIGHTS,
    },
]

for fold_number in range(1, 5):
    candidates.append({
        "model": f"CV Fold {fold_number}",
        "group": "cross_validation",
        "weights": (
            CV_RUNS_DIRECTORY
            / f"taco10_yolo26n_fold_{fold_number}"
            / "weights"
            / "best.pt"
        ),
    })

for candidate in candidates:
    weights = candidate["weights"]
    print(candidate["model"], "->", weights)

    if not weights.exists():
        raise FileNotFoundError(
            f"Checkpoint not found: {weights}"
        )

Training 1 -> /content/drive/MyDrive/YOLO/runs/taco10_yolo26n/weights/best.pt
Training 2 -> /content/drive/MyDrive/YOLO/runs/taco10_yolo26n-2/weights/best.pt
CV Fold 1 -> /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_1/weights/best.pt
CV Fold 2 -> /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_2/weights/best.pt
CV Fold 3 -> /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_3/weights/best.pt
CV Fold 4 -> /content/drive/MyDrive/YOLO_2/runs/cross_validation/taco10_yolo26n_fold_4/weights/best.pt

In [10]:
TEST_RESULTS_DIRECTORY = (
    CV_RUNS_DIRECTORY / "common_test_evaluation"
)
TEST_RESULTS_DIRECTORY.mkdir(
    parents=True,
    exist_ok=True,
)

test_results = []

for candidate in candidates:
    print(f"\nTesting {candidate['model']}")

    model = YOLO(str(candidate["weights"]))

    metrics = model.val(
        data=str(DATA_YAML),
        split="test",
        imgsz=960,
        batch=8,
        workers=2,
        plots=True,
        verbose=False,
        project=str(TEST_RESULTS_DIRECTORY),
        name=candidate["model"]
            .lower()
            .replace(" ", "_"),
        exist_ok=True,
    )

    test_results.append({
        "model": candidate["model"],
        "group": candidate["group"],
        "precision": metrics.box.mp,
        "recall": metrics.box.mr,
        "mAP50": metrics.box.map50,
        "mAP50-95": metrics.box.map,
    })

Testing Training 1
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf': 100% ━━━━━━━━━━━━ 755.1KB 117.9MB/s 0.0s
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 136.2±26.3 MB/s, size: 1375.6 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 287.6it/s 0.5s
val: New cache created: /content/taco_yolo/labels/test/batch_1.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.9it/s 10.2s
                   all        150        485       0.31      0.233      0.201       0.15
Speed: 5.3ms preprocess, 15.4ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/training_1

Testing Training 2
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4360.1±890.3 MB/s, size: 1730.3 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1.cache... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 57.2Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                   all        150        485      0.357      0.278      0.213      0.153
Speed: 3.4ms preprocess, 8.4ms inference, 0.0ms loss, 0.3ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/training_2

Testing CV Fold 1
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3887.1±792.0 MB/s, size: 1919.9 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1.cache... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 37.0Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.2s
                   all        150        485      0.374      0.297      0.269      0.186
Speed: 4.0ms preprocess, 8.4ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/cv_fold_1

Testing CV Fold 2
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 3393.9±356.2 MB/s, size: 1650.5 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1.cache... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 39.3Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.8it/s 10.8s
                   all        150        485      0.346      0.244      0.234      0.174
Speed: 3.3ms preprocess, 8.6ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/cv_fold_2

Testing CV Fold 3
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4538.8±720.7 MB/s, size: 2235.0 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1.cache... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 41.9Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.1s
                   all        150        485      0.247      0.302      0.233      0.168
Speed: 4.3ms preprocess, 9.6ms inference, 0.0ms loss, 0.5ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/cv_fold_3

Testing CV Fold 4
Ultralytics 8.4.136 🚀 Python-3.13.15 torch-2.11.0+cu128 CUDA:0 (Tesla T4, 14913MiB)
YOLO26n summary (fused): 122 layers, 2,376,786 parameters, 0 gradients, 5.3 GFLOPs
val: Fast image access ✅ (ping: 0.0±0.0 ms, read: 4379.7±1050.2 MB/s, size: 1656.3 KB)
val: Scanning /content/taco_yolo/labels/test/batch_1.cache... 150 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 150/150 52.4Mit/s 0.0s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 19/19 1.7it/s 11.0s
                   all        150        485      0.362      0.258      0.234      0.177
Speed: 4.7ms preprocess, 8.5ms inference, 0.0ms loss, 0.4ms postprocess per image
Results saved to /content/drive/MyDrive/YOLO_2/runs/cross_validation/common_test_evaluation/cv_fold_4

NameError: name 'pd' is not defined

In [13]:
test_results_df = pd.DataFrame(test_results)
display(test_results_df)

        model             group  precision    recall     mAP50  mAP50-95
0  Training 1      single_split   0.310048  0.233260  0.201001  0.150287
1  Training 2      single_split   0.357134  0.277988  0.212594  0.152525
2   CV Fold 1  cross_validation   0.373825  0.297314  0.269232  0.186291
3   CV Fold 2  cross_validation   0.346034  0.243695  0.233916  0.173992
4   CV Fold 3  cross_validation   0.246806  0.302375  0.232978  0.168367
5   CV Fold 4  cross_validation   0.362130  0.258383  0.234329  0.177217